/* A packrat parser generated by PackCC 2.0.3 */

#ifndef PCC_INCLUDED_CHESTER_PARSE_H
#define PCC_INCLUDED_CHESTER_PARSE_H

#include "chester.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct chester_peg_context_tag chester_peg_context_t;

chester_peg_context_t *chester_peg_create(suite_t *auxil);
int chester_peg_parse(chester_peg_context_t *ctx, char **ret);
void chester_peg_destroy(chester_peg_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_CHESTER_PARSE_H */
